# Generated by Django 5.0.3 on 2024-03-27 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_name",
            new_name="pass1",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="pass2",
        ),
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
