# Generated by Django 5.0.3 on 2024-03-27 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_last_name_user_pass1_rename_name_user_pass2_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Userdb",
        ),
    ]
