# Generated by Django 5.0.3 on 2024-03-27 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_user_userdb"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Userdb",
            new_name="User",
        ),
    ]
